### PR TITLE
PLAT-334 update packages

### PR DESCRIPTION
**Pull request by jrschumacher**

### CODE REVIEW

**Review by pbacon-blaber — CHANGES_REQUESTED** [review]
can you generate the `package-lock.json` file as well?

**Comment by pbacon-blaber** [comment]
> can you generate the `package-lock.json` file as well?

Actually, why is there no package-lock for this repo?

**Comment by dmihalcik-virtru** [comment]
Some quick googling:

- [package-lock.json is ignored (or maybe just advisory?) for library projects](https://stackoverflow.com/a/44904494)
- the original project this forked from doesn't have one because [Only apps should have lockfiles
](https://github.com/airbnb/javascript/blob/master/.gitignore#L5), a stronger statement than 'npm ignores these files'

**Review by dmihalcik-virtru — APPROVED** [review]

**Review by pbacon-blaber — APPROVED** [review]

**Comment by jrschumacher** [comment]
Yep, I don't advise it. I've made this mistake in the past and it has bitten me hard.

**Pull request merged**
